version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tidio
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - my-datavolume:/var/lib/mysql

volumes:
  my-datavolume:
